/* automatically generated by rust-bindgen 0.69.0 */

pub const TNUM_TSKID: i32 = 3;
pub const TSKID_1_1: i32 = 1;
pub const TSKID_2_1: i32 = 2;
pub const LOGTASK: i32 = 3;
pub const TNUM_SEMID: i32 = 2;
pub const SERIAL_RCV_SEM1: i32 = 1;
pub const SERIAL_SND_SEM1: i32 = 2;
pub const TNUM_FLGID: i32 = 0;
pub const TNUM_DTQID: i32 = 0;
pub const TNUM_PDQID: i32 = 0;
pub const TNUM_MTXID: i32 = 0;
pub const TNUM_SPNID: i32 = 0;
pub const TNUM_MPFID: i32 = 0;
pub const TNUM_CYCID: i32 = 0;
pub const TNUM_ALMID: i32 = 0;
pub const TNUM_ISRID: i32 = 1;
pub const ISR_SIO: i32 = 1;
pub const TNUM_INIRTN: i32 = 7;
pub const TNUM_TERRTN: i32 = 4;
